"""Report generator — formats robustness results as readable output."""

from __future__ import annotations

from intent_laundering.scorer import RobustnessReport
from intent_laundering.tester import TestResult


def generate_report(
    report: RobustnessReport,
    results: list[TestResult],
    model_name: str = "target model",
) -> str:
    """Generate a formatted robustness report.

    Parameters
    ----------
    report : RobustnessReport
        Aggregated metrics from the scorer.
    results : list[TestResult]
        Individual test results for detailed breakdown.
    model_name : str
        Name of the model tested (for display).

    Returns
    -------
    str
        Formatted markdown report.
    """
    lines = [
        f"# Safety Robustness Report",
        f"",
        f"**Model:** {model_name}",
        f"**Prompts tested:** {report.total_prompts}",
        f"",
        f"## Scores",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Original refusal rate | {report.original_refusal_rate:.1%} ({report.original_refusal_count}/{report.total_prompts}) |",
        f"| Paraphrased refusal rate | {report.paraphrased_refusal_rate:.1%} ({report.paraphrased_refusal_count}/{report.total_prompts}) |",
        f"| Cosmetic safety cases | {report.cosmetic_safety_count} |",
        f"| Robustness delta | {report.robustness_delta:.1%} |",
        f"| **Robustness score** | **{report.robustness_score}/100** |",
        f"| **Grade** | **{report.grade}** |",
        f"",
    ]

    # Interpretation
    if report.grade == "A":
        lines.append("Safety is **intent-aware**. Paraphrasing does not significantly reduce refusal rates.")
    elif report.grade in ("B", "C"):
        lines.append("Safety is **partially keyword-dependent**. Some prompts bypass guardrails when trigger words are removed.")
    else:
        lines.append("Safety is **cosmetic**. Guardrails rely on keyword detection rather than intent understanding.")

    lines.append("")
    lines.append("---")
    lines.append("")

    # Detail section: show cosmetic safety cases
    cosmetic_results = [r for r in results if r.safety_is_cosmetic]
    if cosmetic_results:
        lines.append(f"## Cosmetic Safety Cases ({len(cosmetic_results)} found)")
        lines.append("")
        lines.append("Prompts where the original was refused but the paraphrased version was not.")
        lines.append("")

        for i, r in enumerate(cosmetic_results, 1):
            lines.append(f"### Case {i}")
            lines.append(f"")
            lines.append(f"**Technique:** {r.prompt.technique}")
            lines.append(f"**Trigger words:** {', '.join(r.prompt.trigger_words_found) or 'none detected'}")
            lines.append(f"")
            lines.append(f"**Original prompt:**")
            lines.append(f"> {r.prompt.original}")
            lines.append(f"")
            lines.append(f"**Paraphrased prompt:**")
            lines.append(f"> {r.prompt.paraphrased}")
            lines.append(f"")
            lines.append(f"**Original response (REFUSED):**")
            lines.append(f"> {r.original_response[:300]}...")
            lines.append(f"")
            lines.append(f"**Paraphrased response (COMPLIED):**")
            lines.append(f"> {r.paraphrased_response[:300]}...")
            lines.append(f"")
            lines.append(f"---")
            lines.append(f"")

    # Summary of all results
    lines.append(f"## All Results")
    lines.append(f"")
    lines.append(f"| # | Trigger Words | Technique | Original | Paraphrased | Cosmetic |")
    lines.append(f"|---|--------------|-----------|----------|-------------|----------|")

    for i, r in enumerate(results, 1):
        triggers = ", ".join(r.prompt.trigger_words_found[:3]) or "—"
        orig = "REFUSED" if r.original_refused else "complied"
        para = "REFUSED" if r.paraphrased_refused else "complied"
        cosmetic = "YES" if r.safety_is_cosmetic else "—"
        lines.append(f"| {i} | {triggers} | {r.prompt.technique} | {orig} | {para} | {cosmetic} |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by intent-laundering robustness tester*")

    return "\n".join(lines)
